# Generated by Django 5.1.1 on 2024-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("link", models.URLField(blank=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
