# Generated by Django 5.1.1 on 2024-10-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0002_tag_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="portfolioapp.tag"),
        ),
    ]
