# Generated by Django 5.1.1 on 2024-10-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0003_alter_project_date_posted_alter_project_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
