# Generated by Django 4.2.16 on 2025-09-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0004_alter_project_options_project_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/branding/")),
                ("link", models.URLField(blank=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("tags", models.ManyToManyField(blank=True, to="portfolioapp.tag")),
            ],
            options={
                "verbose_name": "Branding Project",
                "verbose_name_plural": "Branding Projects",
                "ordering": ["order"],
            },
        ),
    ]
