# Generated by Django 4.2.16 on 2025-09-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0005_brandingproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("mockup_image_1", models.ImageField(upload_to="images/social_media/")),
                ("mockup_image_2", models.ImageField(upload_to="images/social_media/")),
                ("mockup_image_3", models.ImageField(upload_to="images/social_media/")),
                ("about", models.TextField()),
                ("tools", models.TextField()),
                ("goals", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Social Media Post",
                "verbose_name_plural": "Social Media Posts",
                "ordering": ["order"],
            },
        ),
    ]
