# Generated by Django 4.2.16 on 2025-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0006_socialmediapost"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileLandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "mockup_image_1",
                    models.ImageField(upload_to="images/mobile_landing/"),
                ),
                (
                    "mockup_image_2",
                    models.ImageField(upload_to="images/mobile_landing/"),
                ),
                (
                    "mockup_image_3",
                    models.ImageField(upload_to="images/mobile_landing/"),
                ),
                (
                    "mockup_image_4",
                    models.ImageField(upload_to="images/mobile_landing/"),
                ),
                (
                    "mockup_image_5",
                    models.ImageField(upload_to="images/mobile_landing/"),
                ),
                (
                    "mockup_image_6",
                    models.ImageField(upload_to="images/mobile_landing/"),
                ),
                ("about", models.TextField()),
                ("tools", models.TextField()),
                ("goals", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Mobile Landing Page",
                "verbose_name_plural": "Mobile Landing Pages",
                "ordering": ["order"],
            },
        ),
    ]
