# Generated by Django 4.2.16 on 2025-09-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0007_mobilelandingpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilelandingpage",
            old_name="about",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="mobilelandingpage",
            old_name="mockup_image_1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="goals",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="mockup_image_2",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="mockup_image_3",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="mockup_image_4",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="mockup_image_5",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="mockup_image_6",
        ),
        migrations.RemoveField(
            model_name="mobilelandingpage",
            name="tools",
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="tags",
            field=models.ManyToManyField(blank=True, to="portfolioapp.tag"),
        ),
    ]
