# Generated by Django 4.2.16 on 2025-09-15 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0008_rename_about_mobilelandingpage_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandingproject",
            options={
                "ordering": ["order"],
                "verbose_name": "Brand Design",
                "verbose_name_plural": "Brand Design",
            },
        ),
        migrations.AlterModelOptions(
            name="mobilelandingpage",
            options={
                "ordering": ["order"],
                "verbose_name": "Mobile Landing Pages",
                "verbose_name_plural": "Mobile Landing Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="socialmediapost",
            options={
                "ordering": ["order"],
                "verbose_name": "Social Media Design",
                "verbose_name_plural": "Social Media Design",
            },
        ),
    ]
