# Generated by Django 4.2.16 on 2025-09-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0009_alter_brandingproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingproject",
            name="about_brand",
            field=models.TextField(blank=True, help_text="About brand section content"),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="color_palette_image",
            field=models.ImageField(
                blank=True,
                help_text="Color palette section image",
                upload_to="images/branding/colors/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="goals",
            field=models.TextField(blank=True, help_text="Goals section content"),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="logos_image",
            field=models.ImageField(
                blank=True,
                help_text="Logos section image",
                upload_to="images/branding/logos/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="others_image",
            field=models.ImageField(
                blank=True,
                help_text="Others section image",
                upload_to="images/branding/others/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="packing_image",
            field=models.ImageField(
                blank=True,
                help_text="Packing section image",
                upload_to="images/branding/packing/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="posters_banners_image",
            field=models.ImageField(
                blank=True,
                help_text="Posters & banners section image",
                upload_to="images/branding/posters/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="social_media_image",
            field=models.ImageField(
                blank=True,
                help_text="Social media section image",
                upload_to="images/branding/social/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="typefaces_image",
            field=models.ImageField(
                blank=True,
                help_text="Typefaces section image",
                upload_to="images/branding/typefaces/",
            ),
        ),
    ]
