# Generated by Django 4.2.16 on 2025-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0010_brandingproject_about_brand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandingproject",
            name="packing_image",
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="packaging_image",
            field=models.ImageField(
                blank=True,
                help_text="Packaging section image",
                upload_to="images/branding/packaging/",
            ),
        ),
        migrations.AddField(
            model_name="brandingproject",
            name="tools_apps",
            field=models.TextField(
                blank=True, help_text="Tools & Apps section content"
            ),
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="about_brand",
            field=models.TextField(blank=True, help_text="About brand section content"),
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="color_palette_image",
            field=models.ImageField(
                blank=True,
                help_text="Color palette section image",
                upload_to="images/mobile_landing/colors/",
            ),
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="goals",
            field=models.TextField(blank=True, help_text="Goals section content"),
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="typefaces_image",
            field=models.ImageField(
                blank=True,
                help_text="Typefaces section image",
                upload_to="images/mobile_landing/typefaces/",
            ),
        ),
    ]
