# Generated by Django 4.2.16 on 2025-09-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0011_remove_brandingproject_packing_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_1",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_2",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_3",
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="landing_pages_image",
            field=models.ImageField(
                blank=True,
                help_text="Landing Pages section image",
                upload_to="images/mobile_landing/pages/",
            ),
        ),
        migrations.AddField(
            model_name="mobilelandingpage",
            name="tools_apps",
            field=models.TextField(
                blank=True, help_text="Tools & Apps section content"
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="category",
            field=models.CharField(blank=True, help_text="项目分类", max_length=128),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="image",
            field=models.ImageField(
                blank=True, help_text="项目展示图片", upload_to="images/social_media/"
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="主页预览卡片图片",
                upload_to="images/social_media/preview/",
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="about",
            field=models.TextField(blank=True, help_text="About 部分的文字介绍"),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="goals",
            field=models.TextField(blank=True, help_text="Goals 部分的文字介绍"),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="tools",
            field=models.TextField(blank=True, help_text="Tools & Software 部分的文字介绍"),
        ),
        migrations.CreateModel(
            name="PowerPointPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="PowerPoint Presentations", max_length=128
                    ),
                ),
                (
                    "powerpoint_link_url",
                    models.URLField(
                        blank=True, help_text="PowerPoint presentation link URL"
                    ),
                ),
                (
                    "about_content",
                    models.TextField(
                        default="This comprehensive business presentation demonstrates professional design principles, effective visual hierarchy, and compelling storytelling techniques. Created for business and creative projects, it showcases brand design concepts, user experience methodologies, and strategic project planning.",
                        help_text="About section content",
                    ),
                ),
                (
                    "key_features_content",
                    models.TextField(
                        default="• Professional visual design with consistent branding<br />• Clear information hierarchy and flow<br />• Interactive elements and engaging transitions<br />• Comprehensive project documentation<br />• Strategic planning and execution frameworks",
                        help_text="Key Features section content (HTML allowed)",
                    ),
                ),
                (
                    "tools_software_content",
                    models.TextField(
                        default="Microsoft PowerPoint, Adobe Creative Suite, Figma",
                        help_text="Tools & Software section content",
                    ),
                ),
                (
                    "canvas_link_title",
                    models.CharField(
                        default="View Complete Presentation",
                        help_text="Canvas link section title",
                        max_length=128,
                    ),
                ),
                (
                    "canvas_link_description",
                    models.TextField(
                        default="Access the full interactive presentation with all slides, animations, and detailed content on Canvas.",
                        help_text="Canvas link section description",
                    ),
                ),
                (
                    "canvas_link_url",
                    models.URLField(blank=True, help_text="Canvas presentation URL"),
                ),
                (
                    "canvas_link_text",
                    models.CharField(
                        default="Open in Canvas",
                        help_text="Canvas link button text",
                        max_length=50,
                    ),
                ),
                (
                    "preview_title",
                    models.CharField(
                        default="Presentation Preview",
                        help_text="Preview section title",
                        max_length=128,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Full preview image for the presentation detail page",
                        upload_to="images/powerpoint/",
                    ),
                ),
                (
                    "home_preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Home page preview image (recommended size: 1136×300px)",
                        upload_to="images/powerpoint/home_preview/",
                    ),
                ),
                (
                    "target_audience_content",
                    models.TextField(
                        default="Business professionals, stakeholders, and decision-makers seeking comprehensive project insights and strategic recommendations.",
                        help_text="Target Audience section content",
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this presentation is active"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="portfolioapp.tag")),
            ],
            options={
                "verbose_name": "PowerPoint Presentation",
                "verbose_name_plural": "PowerPoint Presentations",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EcommerceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/ecommerce/")),
                ("link", models.URLField(blank=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "about_project",
                    models.TextField(
                        blank=True, help_text="About project section content"
                    ),
                ),
                (
                    "goals",
                    models.TextField(blank=True, help_text="Goals section content"),
                ),
                (
                    "tools_apps",
                    models.TextField(
                        blank=True, help_text="Tools & Apps section content"
                    ),
                ),
                (
                    "design_process_image",
                    models.ImageField(
                        blank=True,
                        help_text="Design process section image",
                        upload_to="images/ecommerce/process/",
                    ),
                ),
                (
                    "user_interface_image",
                    models.ImageField(
                        blank=True,
                        help_text="User interface section image",
                        upload_to="images/ecommerce/ui/",
                    ),
                ),
                (
                    "mobile_design_image",
                    models.ImageField(
                        blank=True,
                        help_text="Mobile design section image",
                        upload_to="images/ecommerce/mobile/",
                    ),
                ),
                (
                    "product_pages_image",
                    models.ImageField(
                        blank=True,
                        help_text="Product pages section image",
                        upload_to="images/ecommerce/products/",
                    ),
                ),
                (
                    "checkout_flow_image",
                    models.ImageField(
                        blank=True,
                        help_text="Checkout flow section image",
                        upload_to="images/ecommerce/checkout/",
                    ),
                ),
                (
                    "others_image",
                    models.ImageField(
                        blank=True,
                        help_text="Others section image",
                        upload_to="images/ecommerce/others/",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="portfolioapp.tag")),
            ],
            options={
                "verbose_name": "E-commerce Design",
                "verbose_name_plural": "E-commerce Design",
                "ordering": ["order"],
            },
        ),
    ]
