# Generated by Django 4.2.16 on 2025-09-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0011_remove_brandingproject_packing_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilelandingpage",
            name="landing_pages_image",
            field=models.ImageField(
                blank=True,
                help_text="Landing Pages section image",
                upload_to="images/mobile_landing/pages/",
            ),
        ),
    ]
