# Generated by Django 4.2.16 on 2025-09-28 04:02

from django.db import migrations, connection


def safe_remove_columns(apps, schema_editor):
    """Safely remove columns if they exist"""
    with connection.cursor() as cursor:
        # Check if columns exist before trying to remove them
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='portfolioapp_socialmediapost' 
            AND column_name IN ('mockup_image_1', 'mockup_image_2', 'mockup_image_3')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Remove columns that actually exist
        for column in existing_columns:
            cursor.execute(f'ALTER TABLE portfolioapp_socialmediapost DROP COLUMN IF EXISTS {column}')


def reverse_safe_remove_columns(apps, schema_editor):
    """Reverse operation - do nothing as we can't recreate the columns"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0012_remove_socialmediapost_mockup_image_1_and_more"),
    ]

    operations = [
        migrations.RunPython(safe_remove_columns, reverse_safe_remove_columns),
    ]
