# Generated by Django 4.2.16 on 2025-09-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0012_mobilelandingpage_landing_pages_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="mockup_image_1_text",
            field=models.CharField(
                default="Design 01", help_text="拍立得相纸1的文本", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="mockup_image_2_text",
            field=models.CharField(
                default="Design 02", help_text="拍立得相纸2的文本", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="mockup_image_3_text",
            field=models.CharField(
                default="Design 03", help_text="拍立得相纸3的文本", max_length=50
            ),
        ),
    ]
