# Generated by Django 4.2.16 on 2025-09-28 04:02

from django.db import migrations, connection


def safe_remove_columns(apps, schema_editor):
    """Safely remove columns if they exist"""
    with connection.cursor() as cursor:
        # For SQLite, we'll try to remove columns and ignore errors if they don't exist
        columns_to_remove = ['mockup_image_1', 'mockup_image_2', 'mockup_image_3']
        
        # Remove columns that might exist
        for column in columns_to_remove:
            try:
                cursor.execute(f'ALTER TABLE portfolioapp_socialmediapost DROP COLUMN {column}')
            except Exception:
                # Column doesn't exist, which is fine
                pass


def reverse_safe_remove_columns(apps, schema_editor):
    """Reverse operation - do nothing as we can't recreate the columns"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0012_remove_socialmediapost_mockup_image_1_and_more"),
    ]

    operations = [
        migrations.RunPython(safe_remove_columns, reverse_safe_remove_columns),
    ]
