# Generated by Django 4.2.16 on 2025-09-28 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0013_auto_20250928_0402"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_1",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_2",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_3",
        ),
    ]
