# Generated by Django 4.2.16 on 2025-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0014_ecommerceproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerPointPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="PowerPoint Presentations", max_length=128
                    ),
                ),
                (
                    "about_content",
                    models.TextField(
                        default="This comprehensive business presentation demonstrates professional design principles, effective visual hierarchy, and compelling storytelling techniques. Created for business and creative projects, it showcases brand design concepts, user experience methodologies, and strategic project planning.",
                        help_text="About section content",
                    ),
                ),
                (
                    "key_features_content",
                    models.TextField(
                        default="• Professional visual design with consistent branding<br />• Clear information hierarchy and flow<br />• Interactive elements and engaging transitions<br />• Comprehensive project documentation<br />• Strategic planning and execution frameworks",
                        help_text="Key Features section content (HTML allowed)",
                    ),
                ),
                (
                    "tools_software_content",
                    models.TextField(
                        default="Microsoft PowerPoint, Adobe Creative Suite, Figma",
                        help_text="Tools & Software section content",
                    ),
                ),
                (
                    "canvas_link_title",
                    models.CharField(
                        default="View Complete Presentation",
                        help_text="Canvas link section title",
                        max_length=128,
                    ),
                ),
                (
                    "canvas_link_description",
                    models.TextField(
                        default="Access the full interactive presentation with all slides, animations, and detailed content on Canvas.",
                        help_text="Canvas link section description",
                    ),
                ),
                (
                    "canvas_link_url",
                    models.URLField(blank=True, help_text="Canvas presentation URL"),
                ),
                (
                    "canvas_link_text",
                    models.CharField(
                        default="Open in Canvas",
                        help_text="Canvas link button text",
                        max_length=50,
                    ),
                ),
                (
                    "preview_title",
                    models.CharField(
                        default="Presentation Preview",
                        help_text="Preview section title",
                        max_length=128,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Preview image for the presentation",
                        upload_to="images/powerpoint/",
                    ),
                ),
                (
                    "preview_image_caption",
                    models.TextField(
                        default="Sample slides showcasing design consistency and professional layout",
                        help_text="Preview image caption",
                    ),
                ),
                (
                    "design_approach_content",
                    models.TextField(
                        default="The presentation follows a clean, modern design aesthetic with consistent typography, color schemes, and visual elements. Each slide is carefully crafted to maintain audience engagement while effectively communicating complex information through visual storytelling.",
                        help_text="Design Approach section content",
                    ),
                ),
                (
                    "target_audience_content",
                    models.TextField(
                        default="Business professionals, stakeholders, and decision-makers seeking comprehensive project insights and strategic recommendations.",
                        help_text="Target Audience section content",
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this presentation is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "PowerPoint Presentation",
                "verbose_name_plural": "PowerPoint Presentations",
                "ordering": ["order"],
            },
        ),
    ]
