# Generated by Django 4.2.16 on 2025-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0014_remove_socialmediapost_mockup_image_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/ecommerce/')),
                ('link', models.URLField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('about_project', models.TextField(blank=True, help_text='About project section content')),
                ('goals', models.TextField(blank=True, help_text='Goals section content')),
                ('tools_apps', models.TextField(blank=True, help_text='Tools & Apps section content')),
                ('design_process_image', models.ImageField(blank=True, help_text='Design process section image', upload_to='images/ecommerce/process/')),
                ('user_interface_image', models.ImageField(blank=True, help_text='User interface section image', upload_to='images/ecommerce/ui/')),
                ('mobile_design_image', models.ImageField(blank=True, help_text='Mobile design section image', upload_to='images/ecommerce/mobile/')),
                ('product_pages_image', models.ImageField(blank=True, help_text='Product pages section image', upload_to='images/ecommerce/products/')),
                ('checkout_flow_image', models.ImageField(blank=True, help_text='Checkout flow section image', upload_to='images/ecommerce/checkout/')),
                ('others_image', models.ImageField(blank=True, help_text='Others section image', upload_to='images/ecommerce/others/')),
                ('tags', models.ManyToManyField(blank=True, to='portfolioapp.tag')),
            ],
            options={
                'verbose_name': 'E-commerce Design',
                'verbose_name_plural': 'E-commerce Design',
                'ordering': ['order'],
            },
        ),
    ]
