# Generated by Django 4.2.16 on 2025-09-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0015_powerpointpresentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerpointpresentation",
            name="powerpoint_link_url",
            field=models.URLField(
                blank=True, help_text="PowerPoint presentation link URL"
            ),
        ),
    ]
