# Generated by Django 4.2.16 on 2025-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0016_powerpointpresentation_powerpoint_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerpointpresentation",
            name="tags",
            field=models.ManyToManyField(blank=True, to="portfolioapp.tag"),
        ),
    ]
