# Generated by Django 4.2.16 on 2025-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0016_auto_20250928_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='category',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='instagram', help_text='Social media platform category', max_length=20),
        ),
    ]
