# Generated by Django 4.2.16 on 2025-09-26 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0017_powerpointpresentation_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="powerpointpresentation",
            name="design_approach_content",
        ),
        migrations.RemoveField(
            model_name="powerpointpresentation",
            name="preview_image_caption",
        ),
    ]
