# Generated by Django 4.2.16 on 2025-09-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolioapp",
            "0018_remove_powerpointpresentation_design_approach_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="powerpointpresentation",
            name="home_preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Home page preview image (recommended size: 1136×300px)",
                upload_to="images/powerpoint/home_preview/",
            ),
        ),
        migrations.AlterField(
            model_name="powerpointpresentation",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Full preview image for the presentation detail page",
                upload_to="images/powerpoint/",
            ),
        ),
    ]
