# Generated by Django 4.2.16 on 2025-09-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0019_powerpointpresentation_home_preview_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="主页预览卡片图片",
                upload_to="images/social_media/preview/",
            ),
        ),
    ]
