# Generated by Django 4.2.16 on 2025-09-28 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0019_auto_20250928_1256"),
    ]

    operations = []
