# Generated by Django 4.2.16 on 2025-09-27 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0020_socialmediapost_preview_image"),
    ]

    operations = []
