# Generated by Django 4.2.16 on 2025-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0021_auto_20250927_1114"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_1",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_1_text",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_2",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_2_text",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_3",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="mockup_image_3_text",
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="image",
            field=models.ImageField(
                blank=True, help_text="项目展示图片", upload_to="images/social_media/"
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="about",
            field=models.TextField(blank=True, help_text="About 部分的文字介绍"),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="goals",
            field=models.TextField(blank=True, help_text="Goals 部分的文字介绍"),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="tools",
            field=models.TextField(blank=True, help_text="Tools & Software 部分的文字介绍"),
        ),
    ]
