# Generated by Django 4.2.16 on 2025-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0022_auto_20250928_1256'),
    ]

    operations = [
        # This is a placeholder migration to resolve the missing dependency
        # It appears this migration was referenced but never created
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
    ]