# Generated by Django 4.2.16 on 2025-09-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0022_remove_socialmediapost_mockup_image_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilelandingpage",
            name="tools_apps",
            field=models.TextField(
                blank=True, help_text="Tools & Apps section content"
            ),
        ),
    ]
