# Generated by Django 4.2.16 on 2025-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0023_auto_20250928_1256"),
    ]

    operations = [
        # This migration represents the SocialMediaPost category field addition
        # that was originally in the missing 0024_socialmediapost_category.py
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL since the field was already added in 0017
            reverse_sql="SELECT 1;"
        ),
    ]
