# Generated by Django 4.2.16 on 2025-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0023_auto_20250928_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='category',
            field=models.CharField(blank=True, help_text='项目分类', max_length=128),
        ),
    ]