
# Generated by fix_migration_conflict.py

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('portfolioapp', '0024_auto_20250928_1256'),
    ]
    
    operations = [
        # 这是一个修复迁移，用于解决字段已存在的冲突
        # landing_pages_image 字段已经存在于数据库中
    ]
