# Generated by Django 4.2.16 on 2025-09-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_socialmediapost_category'),
    ]

    operations = [
        # This is a merge migration that consolidates all the previous fix attempts
        # It ensures compatibility between local and Heroku environments
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL, all model changes were already applied
            reverse_sql="SELECT 1;"
        ),
    ]