# Generated by Django 4.2.16 on 2025-09-28 17:45

from django.db import migrations, connection


def check_and_fix_migrations(apps, schema_editor):
    """检查并修复迁移问题"""
    # 检查是否需要跳过某些迁移操作
    with connection.cursor() as cursor:
        # 检查landing_pages_image字段是否已经存在
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='portfolioapp_mobilelandingpage' 
            AND column_name='landing_pages_image'
        """)
        landing_pages_exists = cursor.fetchone()
        
        # 如果字段已存在，我们不需要执行任何操作
        # 这个函数主要是为了确保迁移能够顺利进行
        pass


def reverse_check_and_fix_migrations(apps, schema_editor):
    """反向操作"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_socialmediapost_category'),
    ]

    operations = [
        # 检查并修复迁移问题
        migrations.RunPython(check_and_fix_migrations, reverse_check_and_fix_migrations),
        
        # 确保所有模型变更都已应用
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
    ]