# Generated by Django 4.2.16 on 2025-09-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_socialmediapost_category'),
    ]

    operations = [
        # This migration ensures compatibility between local and Heroku environments
        # All model changes have already been applied to the database
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL, all model changes were already applied
            reverse_sql="SELECT 1;"
        ),
    ]