# Generated by fix_landing_pages_migration.py

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_socialmediapost_category'),
    ]

    operations = [
        # 这是一个安全的迁移，用于解决字段已存在的冲突
        # landing_pages_image字段已经存在于数据库中，无需再次创建
    ]
