# Generated by Django 4.2.16 on 2025-09-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_socialmediapost_category'),
    ]

    operations = [
        # This migration fixes the migration order issue
        # by ensuring all dependencies are properly applied
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
    ]