# Generated by Django 4.2.16 on 2025-09-28 16:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_auto_20250928_1256'),
    ]

    operations = [
        # 这是一个最终的修复迁移，用于解决Heroku部署问题
        # 确保所有迁移都正确应用，而不会出现依赖错误
    ]