# Generated by Django 4.2.16 on 2025-09-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0023_auto_20250928_1256'),
        ('portfolioapp', '0024_socialmediapost_category'),
    ]

    operations = [
        # This migration fixes the inconsistent migration history
        # by explicitly depending on both the last consistent migration
        # and the currently applied migration
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
    ]