# Generated by Django 4.2.16 on 2025-09-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0028_fix_inconsistent_migration'),
    ]

    operations = [
        # This migration ensures all migrations are applied in the correct order
        # and resolves any remaining inconsistencies
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
    ]