# Generated by Django 4.2.16 on 2025-09-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_socialmediapost_category'),
        ('portfolioapp', '0023_mobilelandingpage_tools_apps'),
    ]

    operations = [
        # This migration resolves the conflict between the two migrations
        # that both depend on 0023_auto_20250928_1256
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
    ]