# Generated by Django 4.2.16 on 2025-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0024_auto_20250928_1256"),
        ("portfolioapp", "0026_heroku_comprehensive_fix"),
        ("portfolioapp", "0027_fix_migration_order"),
        ("portfolioapp", "0029_final_migration_fix"),
        ("portfolioapp", "0030_resolve_migration_conflict"),
    ]

    operations = []
