# Generated by Django 4.2.16 on 2025-09-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0031_merge_20250928_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolioapp.tag'),
        ),
    ]
