# Generated by Django 4.2.16 on 2025-09-28 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0033_auto_20250928_2326"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediapost",
            name="tags",
        ),
    ]
