# Generated by Django 4.2.16 on 2025-09-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0034_remove_social_media_tags_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerpointpresentation",
            name="description",
            field=models.TextField(
                default="Professional business presentations showcasing design principles, visual hierarchy, and strategic project planning.",
                help_text="Brief description for preview cards",
            ),
        ),
    ]
