# Generated by Django 4.2.16 on 2025-09-29 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0035_add_powerpoint_description_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="powerpointpresentation",
            name="description",
        ),
    ]
