# Generated by Django 4.2.16 on 2025-10-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolioapp", "0036_remove_powerpoint_description_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionGraphicsProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Main video file (MP4, MOV, etc.)",
                        upload_to="videos/motion_graphics/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="External video URL (YouTube, Vimeo, etc.)",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Preview thumbnail image",
                        upload_to="images/motion_graphics/preview/",
                    ),
                ),
                (
                    "about_project",
                    models.TextField(
                        blank=True, help_text="About project section content"
                    ),
                ),
                (
                    "goals",
                    models.TextField(blank=True, help_text="Goals section content"),
                ),
                (
                    "tools_software",
                    models.TextField(
                        blank=True, help_text="Tools & Software section content"
                    ),
                ),
                (
                    "process_image",
                    models.ImageField(
                        blank=True,
                        help_text="Design process section image",
                        upload_to="images/motion_graphics/process/",
                    ),
                ),
                (
                    "storyboard_image",
                    models.ImageField(
                        blank=True,
                        help_text="Storyboard section image",
                        upload_to="images/motion_graphics/storyboard/",
                    ),
                ),
                (
                    "final_output_image",
                    models.ImageField(
                        blank=True,
                        help_text="Final output section image",
                        upload_to="images/motion_graphics/final/",
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this project is active"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="portfolioapp.tag")),
            ],
            options={
                "verbose_name": "Motion Graphics Project",
                "verbose_name_plural": "Motion Graphics Projects",
                "ordering": ["order"],
            },
        ),
    ]
